### ISSUE TITLE
Did you ever manage to fix this?

### ISSUE THREAD

**Issue by joeyjurjens** [vladox/test-divio-jupyter#1]
Hey,

Did you ever manage to fix [this](https://stackoverflow.com/questions/61331474/failing-docker-install-of-jupyter-on-django) issue? 
I'm having the same issue, but with a different package.

I asked a developer at divio for support, but he ran it locally & it worked just fine.

Hope you got an answer!

**Comment by vladox** [comment]
Hi @joeyjurjens yes actually they recommend me to install Jupyter not using requirements.in but installing directly during the Docker image build. 
If you need an example I may still have it.

**Comment by joeyjurjens** [comment]
I'm happy to hear you managed to fix it! An example would be great, not that familiar with Docker yet. Thanks for replying!

**Comment by joeyjurjens** [comment]
I've managed to fix it. There are multiple ways to fix it actually:

bypass both Aldryn Django and our wheels proxy or remove --no-index from the dockerfile.

Thanks for replying and trying to help, very much appreciated! :D
